server:
  port: 8081

spring:
  #数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.20.4.94:1521:orcl
    username: TOPSIMDEV
    password: E3L#_RxAuWJs
